services:
  - type: web
    name: ptlab2-luxury-shop
    runtime: docker
    plan: free
    region: frankfurt
    branch: master
    autoDeployTrigger: checksPass
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: ptlab2-luxury-shop
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: DB_NAME
        fromDatabase:
          name: ptlab2-luxury-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: ptlab2-luxury-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ptlab2-luxury-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: ptlab2-luxury-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ptlab2-luxury-db
          property: port

databases:
  - name: ptlab2-luxury-db
    databaseName: luxury_shop
    user: luxury_shop
    plan: free
    region: frankfurt
